package com.mxs.huobi.type;

public enum CandlestickPatternType {
    HAMMER,
    INVERTED_HAMMER,
    BULLISH_ENGULFING,
    BEARISH_ENGULFING,
    BULLISH_HARAMI,
    BEARISH_HARAMI,
    BULLISH_PIN_BAR,
    BEARISH_PIN_BAR,
    MORNING_STAR,
    EVENING_STAR,
    THREE_WHITE_SOLDIERS,
    THREE_BLACK_CROWS,
    DOUBT
}
